# -*- coding: utf-8 -*-
{
    "name": "Study Student Portal",
    "summary": "It is a module for managing study abroad portal processes, including student applications, program management, and related activities.",
    "description": """
    It is a module for managing study abroad portal processes, including student applications, program management, and related activities.
""",
    "category": "Study Abroad",
    "author": "Daffodil Software Limited (DSL)",
    "website": "https://daffodilsoft.com/",
    "version": "17.0",
    "depends": ["web", "portal", "dsl_study_core", "hide_powered_by_odoo"],
    "data": [
        # "security/ir.model.access.csv",
        "views/login_view.xml",
        "views/student_dashboard.xml",
        "views/agent_dashboard.xml",
        "views/agent_student_detail.xml",
        "views/student_programs_view.xml",
        "views/student_complaints_view.xml",
        "views/agent_complaints_view.xml",
        "views/student_communication.xml",
        "views/agent_communication.xml",
        "views/portal_layout.xml",
        "views/student_notifications.xml",
        "views/student_sidebar.xml",
        "views/agent_sidebar.xml",
        "views/student_profile.xml",
        "views/student_documents.xml",
        "views/agent_documents.xml",
        "views/agent_profile.xml",
        "views/student_invoices.xml",
        "views/student_security.xml",
        "views/student_sponsor_view.xml",
        "views/agent_invoices.xml",
        "views/agent_security.xml",
        "views/agent_commission.xml",
        "views/agent_contract.xml",
        # "views/student_reg.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "dsl_student_portal/static/src/css/portal_dashboard.css",
            "dsl_student_portal/static/src/css/documents.css",
            "dsl_student_portal/static/src/css/dsl_login.css",
            "dsl_student_portal/static/src/js/portal_notification.js",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
