# models/hr_attendance.py
from odoo import models, fields, api
from datetime import datetime, timedelta
import pytz
import logging

_logger = logging.getLogger(__name__)


class HrAttendance(models.Model):
    _inherit = "hr.attendance"

    # ── Existing flags ───────────────────────────────────────────────────────
    is_late = fields.Boolean(
        string="Is Late", compute="_compute_attendance_flags", store=True
    )
    is_post_noon = fields.Boolean(
        string="Post-Noon Arrival", compute="_compute_attendance_flags", store=True
    )
    is_early_checkout = fields.Boolean(
        string="Early Checkout", compute="_compute_attendance_flags", store=True
    )
    late_minutes = fields.Integer(
        string="Late Minutes", compute="_compute_attendance_flags", store=True
    )
    early_minutes = fields.Integer(
        string="Early Minutes",
        compute="_compute_attendance_flags",
        store=True,
        help="Minutes left early compared to official office end time.",
    )

    # ── Dummy attendance fields ──────────────────────────────────────────────
    auto_generated = fields.Boolean(
        string="Auto Generated",
        default=False,
        readonly=True,
        help="True if this attendance record was auto-generated by the system for Leave or Absent.",
    )
    auto_generated_type = fields.Selection(
        [("leave", "Leave"), ("absent", "Absent"), ("sat_off", "Saturday Off")],
        string="Auto Generated Type",
        readonly=True,
    )

    # ── Status fields ────────────────────────────────────────────────────────
    status_type = fields.Selection(
        [
            ("ok", "On-Time"),
            ("late", "Late"),
            ("post_noon", "Post-Noon Arrival"),
            ("early_checkout", "Early Checkout"),
            ("late_early", "Late & Early Checkout"),
            ("missed_checkout", "Missed Checkout"),
            ("leave", "Leave"),
            ("absent", "Absent"),
            ("sat_off", "Saturday Off"),
        ],
        string="Status Type",
        compute="_compute_status",
        store=False,
    )
    status_label = fields.Char(
        string="Status",
        compute="_compute_status",
        store=False,
    )

    def _format_minutes(self, minutes):
        """Convert minutes to 'Xhr Ymin' format if >= 60, else 'Ymin'"""
        if minutes >= 60:
            hours = minutes // 60
            mins = minutes % 60
            if mins == 0:
                return f"{hours}hr"
            return f"{hours}hr {mins}min"
        return f"{minutes}min"

    # ── Status compute ───────────────────────────────────────────────────────
    @api.depends(
        "auto_generated", "auto_generated_type",
        "is_late", "is_post_noon", "is_early_checkout", "late_minutes", "early_minutes",
        "is_auto_checkout", "employee_id", "check_in",
    )
    def _compute_status(self):
        for att in self:

            # ── Priority 1: Auto-generated dummy rows ────────────────────────
            if att.auto_generated:
                if att.auto_generated_type == "absent":
                    att.status_type = "absent"
                    att.status_label = "Absent"
                elif att.auto_generated_type == "sat_off":
                    att.status_type = "sat_off"
                    att.status_label = "Saturday Off"
                else:
                    att.status_type = "leave"
                    att.status_label = "Leave"
                continue

            if not att.check_in:
                att.status_type = "ok"
                att.status_label = "On-Time"
                continue

            check_date = att.check_in.date()

            # ── Priority 2: Absent check ─────────────────────────────────────
            try:
                absent_log = self.env["absent.deduction.log"].search([
                    ("employee_id", "=", att.employee_id.id),
                    ("check_date", "=", check_date),
                    ("status", "=", "deducted"),
                ], limit=1)
                if absent_log:
                    att.status_type = "absent"
                    att.status_label = "Absent"
                    continue
            except Exception:
                pass

            # ── Priority 3: Manual Leave check ──────────────────────────────
            try:
                leave = self.env["hr.leave"].search([
                    ("employee_id", "=", att.employee_id.id),
                    ("request_date_from", "<=", check_date),
                    ("request_date_to", ">=", check_date),
                    ("state", "in", ["validate", "validate1"]),
                    ("auto_absent", "=", False),
                    ("is_auto_deduction", "=", False),
                ], limit=1)
                if leave:
                    att.status_type = "leave"
                    att.status_label = "Leave"
                    continue
            except Exception:
                pass

            # ── Priority 4: Attendance-based status ──────────────────────────
            if att.is_post_noon:
                att.status_type = "post_noon"
                att.status_label = "Post-Noon Arrival"

            elif att.is_late and att.is_early_checkout:
                late_str = self._format_minutes(att.late_minutes)
                early_str = self._format_minutes(att.early_minutes)
                att.status_type = "late_early"
                att.status_label = f"Late ({late_str}), Early Checkout ({early_str} early)"

            elif att.is_late:
                late_str = self._format_minutes(att.late_minutes)
                att.status_type = "late"
                att.status_label = f"Late ({late_str})"

            elif att.is_early_checkout:
                early_str = self._format_minutes(att.early_minutes)
                att.status_type = "early_checkout"
                att.status_label = f"Early Checkout ({early_str} early)"

            else:
                att.status_type = "ok"
                att.status_label = "On-Time"

            # ── Priority 5: Missed Checkout (append/replace) ─────────────────
            # Only applies to real attendance rows (not auto-generated)
            if att.is_auto_checkout:
                if att.status_type == "ok":
                    att.status_type = "missed_checkout"
                    att.status_label = "Missed Checkout"
                else:
                    att.status_type = "missed_checkout"
                    att.status_label = f"{att.status_label}, Missed Checkout"

    # ── Attendance flags ─────────────────────────────────────────────────────
    @api.depends("check_in", "check_out", "employee_id")
    def _compute_attendance_flags(self):
        print("1")
        gmt6_tz = pytz.timezone('Asia/Dhaka')

        for attendance in self:
            # check_in = pytz.UTC.localize(attendance.check_in).astimezone(gmt6_tz).replace(tzinfo=None) if attendance.check_in else False
            # check_out = pytz.UTC.localize(attendance.check_out).astimezone(gmt6_tz).replace(tzinfo=None) if attendance.check_out else False
            # print(attendance.check_in)
            # print(check_in)
            # print(attendance.check_out)
            # print(check_out)
            if attendance.auto_generated:
                attendance.is_late = False
                attendance.is_post_noon = False
                attendance.is_early_checkout = False
                attendance.late_minutes = 0
                attendance.early_minutes = 0
                continue

            if not attendance.check_in:
                attendance.is_late = False
                attendance.is_post_noon = False
                attendance.is_early_checkout = False
                attendance.late_minutes = 0
                attendance.early_minutes = 0
                continue

            try:
                config = self.env["leave.deduction.config"].get_config(
                    attendance.employee_id.company_id.id
                )
            except Exception as e:
                _logger.warning(f"Could not get config: {str(e)}")
                attendance.is_late = False
                attendance.is_post_noon = False
                attendance.is_early_checkout = False
                attendance.late_minutes = 0
                attendance.early_minutes = 0
                continue

            if not config:
                attendance.is_late = False
                attendance.is_post_noon = False
                attendance.is_early_checkout = False
                attendance.late_minutes = 0
                attendance.early_minutes = 0
                continue

            check_in_time = fields.Datetime.context_timestamp(
                attendance, attendance.check_in
            )
            check_in_float = check_in_time.hour + check_in_time.minute / 60.0

            attendance.is_post_noon = check_in_float > config.noon_threshold_time

            if not attendance.is_post_noon:
                late_threshold = config.office_start_time + (
                    config.late_threshold_minutes / 60.0
                )
                attendance.is_late = check_in_float > late_threshold
                if attendance.is_late:
                    office_start_dt = check_in_time.replace(
                        hour=int(config.office_start_time),
                        minute=int((config.office_start_time % 1) * 60),
                        second=0,
                    )
                    attendance.late_minutes = int(
                        (check_in_time - office_start_dt).total_seconds() / 60
                    )
                else:
                    attendance.late_minutes = 0
            else:
                attendance.is_late = False
                attendance.late_minutes = 0
            if attendance.check_out:
                check_out_time = fields.Datetime.context_timestamp(
                    attendance, attendance.check_out
                )
                check_out_float = check_out_time.hour + check_out_time.minute / 60.0
                attendance.is_early_checkout = (
                    config.early_checkout_start_time
                    <= check_out_float
                    <= config.early_checkout_end_time
                )
                if attendance.is_early_checkout:
                    attendance.early_minutes = max(0, int(
                        (config.office_end_time - check_out_float) * 60
                    ))
                else:
                    attendance.early_minutes = 0
            else:
                attendance.is_early_checkout = False
                attendance.early_minutes = 0

    def convert_to_gmt6(self, dt=None):
        """
        Convert datetime to GMT+6 timezone
        Args:
            dt: datetime object (if None, uses current UTC time)
        Returns:
            datetime object in GMT+6 timezone
        """
        gmt6_tz = pytz.timezone('Asia/Dhaka')  # GMT+6

        if dt is None:
            dt = datetime.now(pytz.UTC)
        elif dt.tzinfo is None:
            dt = pytz.UTC.localize(dt)

        return dt.astimezone(gmt6_tz)

    # ── Create / Write ───────────────────────────────────────────────────────
    @api.model
    def create(self, vals):
        attendance = super().create(vals)
        if not attendance.auto_generated and not self.env.context.get("skip_deduction"):
            attendance._check_and_process_deductions()
        return attendance

    def write(self, vals):
        res = super().write(vals)
        if (
            ("check_in" in vals or "check_out" in vals)
            and not self.env.context.get("skip_deduction")
        ):
            real = self.filtered(lambda a: not a.auto_generated)
            if real:
                real._check_and_process_deductions()
        return res

    # ── Deduction processing ─────────────────────────────────────────────────
    def _check_and_process_deductions(self):
        DeductionLog = self.env["leave.deduction.log"]

        for attendance in self:
            if attendance.auto_generated:
                continue
            if not attendance.employee_id:
                continue

            try:
                config = self.env["leave.deduction.config"].get_config(
                    attendance.employee_id.company_id.id
                )
            except Exception as e:
                _logger.warning(
                    f"Config not found for {attendance.employee_id.company_id.name}: {str(e)}"
                )
                continue

            if not config:
                continue

            employee = attendance.employee_id

            # Rule 2: Post-noon
            if attendance.is_post_noon and attendance.check_in:
                existing = DeductionLog.search([
                    ("employee_id", "=", employee.id),
                    ("deduction_type", "=", "post_noon"),
                    ("attendance_ids", "in", attendance.id),
                ], limit=1)
                if not existing:
                    log = DeductionLog.with_context(from_attendance_system=True).create({
                        "employee_id": employee.id,
                        "deduction_date": attendance.check_in.date(),
                        "deduction_type": "post_noon",
                        "attendance_ids": [(6, 0, [attendance.id])],
                        "notes": f"Check-in at {attendance.check_in} (after 12:00 PM)",
                    })
                    try:
                        log.sudo().action_process()
                    except Exception as e:
                        _logger.error(f"Post-noon deduction failed: {str(e)}")

            # Rule 1: 15-min late
            if attendance.is_late and attendance.check_in and not attendance.is_post_noon:
                current_count = employee.late_check_in_count + 1
                employee.sudo().write({"late_check_in_count": current_count})

                if current_count >= config.late_days_for_deduction:
                    late_atts = self.search([
                        ("employee_id", "=", employee.id),
                        ("is_late", "=", True),
                        ("is_post_noon", "=", False),
                        ("check_in", "<=", attendance.check_in),
                        ("auto_generated", "=", False),
                    ], order="check_in desc", limit=config.late_days_for_deduction)

                    existing = DeductionLog.search([
                        ("employee_id", "=", employee.id),
                        ("deduction_type", "=", "15min_late"),
                        ("attendance_ids", "in", attendance.id),
                    ], limit=1)

                    if not existing and len(late_atts) == config.late_days_for_deduction:
                        log = DeductionLog.with_context(from_attendance_system=True).create({
                            "employee_id": employee.id,
                            "deduction_date": fields.Date.today(),
                            "deduction_type": "15min_late",
                            "attendance_ids": [(6, 0, late_atts.ids)],
                            "notes": f"{config.late_days_for_deduction} late check-ins accumulated",
                        })
                        try:
                            log.sudo().action_process()
                            employee.sudo().reset_late_count()
                        except Exception as e:
                            _logger.error(
                                f"15-min late deduction failed: {str(e)}")

            # Rule 3: Early checkout
            if attendance.is_early_checkout and attendance.check_out:
                existing = DeductionLog.search([
                    ("employee_id", "=", employee.id),
                    ("deduction_type", "=", "early_checkout"),
                    ("attendance_ids", "in", attendance.id),
                ], limit=1)
                if not existing:
                    log = DeductionLog.with_context(from_attendance_system=True).create({
                        "employee_id": employee.id,
                        "deduction_date": attendance.check_out.date(),
                        "deduction_type": "early_checkout",
                        "attendance_ids": [(6, 0, [attendance.id])],
                        "notes": f"Check-out at {attendance.check_out} (early checkout window)",
                    })
                    try:
                        log.sudo().action_process()
                    except Exception as e:
                        _logger.error(
                            f"Early checkout deduction failed: {str(e)}")

    # ── Helper: create dummy attendance ─────────────────────────────────────
    @api.model
    def create_dummy_attendance(self, employee, check_date, att_type):
        """Dummy attendance row created for Leave or Absent."""
        import pytz
        from datetime import time as dt_time

        existing = self.search([
            ("employee_id", "=", employee.id),
            ("auto_generated", "=", True),
            ("auto_generated_type", "=", att_type),
            ("check_in", ">=", fields.Datetime.to_datetime(
                f"{check_date} 00:00:00")),
            ("check_in", "<=", fields.Datetime.to_datetime(
                f"{check_date} 23:59:59")),
        ], limit=1)

        if existing:
            return existing

        tz_name = (
            employee.resource_calendar_id.tz or employee.tz or "UTC"
        )
        try:
            tz = pytz.timezone(tz_name)
        except Exception:
            tz = pytz.utc

        local_dt = datetime.combine(check_date, dt_time(10, 0, 0))
        utc_dt = tz.localize(local_dt).astimezone(
            pytz.utc).replace(tzinfo=None)

        attendance = self.with_context(skip_deduction=True).sudo().create({
            "employee_id": employee.id,
            "check_in": utc_dt,
            "check_out": utc_dt,
            "auto_generated": True,
            "auto_generated_type": att_type,
        })

        _logger.info(
            f"Dummy attendance ({att_type}) created for {employee.name} on {check_date}"
        )
        return attendance
